---
title: "Project Description Outline"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Names of group members

Scott Wright, Cameron Fraser, Alisa Tunonen & Mark Fojas

### Roles & responsibilities of each member

**Scott** worked on:

* Cleaning & wrangling of Bed Capacity Data;
* Bed Capacity analysis scripts and visualisation (plots).Analysis included 
inferential statistics - bootstrapping methods;
* Generated data joining script for group and joined datasets ready for analysis.

**Cameron** worked on:

* Cleaning & wrangling of Geospatial Data;
* Development of R-Shiny Web App (dashboard) inclusive of R-Shiny global, UI and server 
scripts;
* Led the process of merging each group members scripts into the above scripts
of R-Shiny Web App.

**Alisa** worked on:

* Identifying the datasets necessary to answer the questions set by the group as 
part of satisfying the brief; 
* Cleaning and wrangling of Admissions Data (including A&E Admissions);
* Admissions analysis scripts and visualisation (plots).Analysis included
use of predictive modelling. 

**Mark** worked on:

* Cleaning and wrangling of Delayed Discharge Data (inclusive of reviewing 
demographic influences such as age, reasons for delay and deprivation);
* Delayed discharge analysis scripts and visualisation (plots);
* Researched and considered influence of NHS staff numbers/working hours, for 
potential future analysis.

**Everyone** worked on:

* Reviewing the project brief and determining our approach to satisfying it -
posing questions for the collective group to consider, and exploring the areas 
highlighted;
* Dashboard design & layout (wireframe) - agreeing initial and final concepts both visually
and from a functional perspective (with the end user in mind);
* Development of group presentation (including  final delivery & rehearsal).


### Brief description of dashboard topic

The core topic for the dashboard  was the impact that winter might have on 
Scotland's health care system (NHS), primarily in the hospital (acute care) sector. 

Key focus areas and questions to be answered using the information 
provided by the dashboard, were:

1. To what extent is the ‘winter crises’ the media predicts real?;

2. How has winter impacted Scotland’s NHS in the past?;

3. Potential impact in winter 2022;

4. How might the pandemic influence the potential scenario?.

The dashboard outlines our topic in terms of providing insight into Temporal, 
Demographic & Geographic Aspects of the domain, and was designed such to provide 
the theoretical front end user (NHS Administration Staff) with user-friendly
access to information on key performance indicators (KPI's). 

The theoretical client for the project was Public Health Scotland (PHS)

### Stages of the project

The stages of this project were as follows:

**22nd April 2022;**

* Group review and consideration of project brief;
* Agreement on project management approach - communication & collaboration 
methods, action tracking & version control methods;
* Setting up of group repository on github.

**23rd to 24th April 2022;**

* Development & consolidation of group questions and allocation of focus 
areas to each team member, for further research and dataset identification. 
* Selection of datasets;
* Joining of datasets where applicable.

**25th to 26th April:**

* Initial dashboard planning and wireframe;
* Initital data analysis & visualisations.

**27th of April:**

* Continuation of dashboard development and analysis;
* Presentation preparation and rehearsal.

**28th of April:**

* Delivery of group project presentation inclusive of dashboard, to project 
client, Public Health Scotland.

### Which tools were used in the project

* Zoom (predominantly used at weekends when team members were remote working);
* Git/GitHub (collaboration & version control);
* Slack in aid of remote team communication and collaboration;
* R Studio (Integrated Development Environment);
* Morning (9.45am) and afternoon (2.30pm) team stand-ups (Mon-Fri).
* Meeting with Public Health Scotland representative on Monday 

### How did you gather and synthesise requirements for the project?

In the first instance, we needed to create clarity and a mutual understanding
within the group of what the project brief was, what outcomes we had to meet,
and how we would meet such outcomes.Each person within the group 
shared their own interpretation of the brief and their thoughts on how best to 
achieve the project outcomes. We began *"with the end user in mind"* and as a 
result, we reached consensus in an efficient and coordinated manner.

As the project evolved, our group prioritised the development of a dashboard which 
would ultimately, provide enough information, to allow the end user to answer the 
questions set/asked by the project brief.

Our dashboard focused on the following areas;

* Bed Capacity;
* Admissions;
* Delayed Discharge, and to
* Provide the functionality to observe the above through changing variables such 
as specialty, time, year, quarter, season, geographical location 
(health board/hospital), age and social deprivation.


### Motivations for using the data you have chosen

In the planning stages, we established that bed occupancy, number of admissions,
and delayed discharges would be the key performance indicators to gain insights
into the Winter Crisis and it's strain on Scottish NHS Health Boards.

We used a dataset of the NHS Health Boards across Scotland, to give an interactive
map that would allow quick glances into the rate of our key performance indicators
at a health board area. This was done in our summary tab of the dashboard and was
included to allow Public Health Scotland to look at key measures with a geo-spatial
aspect.

We used the dataset on bed occupancy to answer how strained hospitals and health
boards are and we chose to do this because we wanted to have a measure that could
be used to measure current strains on the NHS. This would then be developed to be
a live measure, and allow administrators to re-allocate resources based on live
figures. We allowed comparisons of this measure to be one hopsital against the 
total average rate of bed occupancy, and also compare two hospitals against each
other.

We used the dataset on number of admissions by health board & by hospital to 
look at the changes of number of people admitted against time. This answers the
question whether there is an increased of admissions during the winter period,
and if there is a cyclic trend of admissions - with increased numbers admitted 
during winter versus other times of the year. This was because we were interested
in determining the strain that increased admissions would put on resources, and 
if there was a cyclic trend, it would help planning the allocation of resources 
to change when the rate of admission was high. This dataset also allowed us to 
compare rate of admission before and during the COIVD-19 pandemic - and then we 
used predictive modelling to model the future rate of admissions based on the 
current data trend.

We finally used a dataset based on delayed discharge to answer what demographic 
of patients have an increased time spent in hospitals because we wanted to see 
which individuals are most effected by strains in the NHS. This was set up to 
allow filtering based on a date range and hospitals, again to allow planning of
resources when there was an increased pressure on the NHS.

### Data quality and potential bias, including a brief summary of data cleaning and transformations

According to the About tab on the dataset page/dedicated page online, the data quality ...

The dataset may/may not be biased because ...

To clean the datasets we ...

Geo-spatial data on the Health Boards within Scotland were mapped to give an 
interactive map that highlights the bed occupancy, number of admissions and 
delayed discharge rate within Health Boards. This was done by researching the 
borders of each Health Board and obtaining polygons/shapes to be mapped using
the `leaflet` package. Once this was done, a `join` was performed on the each 
data set - to give each data set an identifier column for Health Boards. This 
would allow the map to filter `plots` and `infoBoxes` when a Health Board was 
clicked. This was all placed upon the __Summary tab__, and had three info Boxes;
the selected Health Board's bed occupancy, admissions and delayed discharge. The
tab also had two plots of the bed occupancy and the A&E targets - both of which 
were split up hospitals within the Health Board.

### How is the data stored and structured

[**Hint**: This page offers a good starting point for understanding the data structure: https://guides.statistics.gov.scot/article/34-understanding-the-data-structure]

The data is in the form of ...

This means ...

Benefits of storing the data like this are ...

### Ethical and legal considerations of the data

[**Hint:** this page contains information on the Open Government License which covers most datasets on statistics.gov.scot: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/]

There are no/There may be ethical considerations, because ...

The datasets are covered by the Open Government License, which means ...